spring:
  application:
    name: react-service

  datasource:
    url: jdbc:mysql://192.168.1.5:3306/react_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: linuxUser
    password: KTPM_247
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.21:8761/eureka
    register-with-eureka: true
    enabled: true
    instance:
      prefer-ip-address: true
      ip-address: 192.168.1.21

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
