
version: '3.7'
services:
  mongo:
    container_name: mongo_db
    image: mongo:4.4.6
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - $HOME/docker-volumes/mongo_db/mongo:/data/db
