spring:
  application:
    name: message-service

  datasource:
    url: jdbc:mysql://192.168.1.10:3306/message_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: linuxUser
    password: KTPM_247
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true