server:
  port: 8083

spring:
  application:
    name: message-service

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.21:8761/eureka
    register-with-eureka: true
    enabled: true
    instance:
      prefer-ip-address: true
      ip-address: 192.168.1.21

